#!/bin/bash

cd /ensembl

# データの取得
perl biomart_inputfile_1.pl > biomart_outputfile_1.txt
perl biomart_inputfile_2.pl > biomart_outputfile_2.txt
perl biomart_inputfile_3.pl > biomart_outputfile_3.txt

# 不要行の削除
sed -i '1,2d' biomart_outputfile_1.txt
sed -i '1,2d' biomart_outputfile_2.txt
sed -i '1,2d' biomart_outputfile_3.txt

# 変換の実行
ruby ./rdf_converter_ensembl_human_grch37/rdf_converter_ensembl_rgch37.rb -g biomart_outputfile_1.txt -e biomart_outputfile_2.txt -x biomart_outputfile_3.txt > /data/ensembl.ttl 

chmod 777 /data/ensembl.ttl
